### ISSUE TITLE
edit README

### ISSUE THREAD

**Issue by kais-siala** [tum-ens/geoclustering#14]
Remove the paragraph of the description,
add the links to black and all-contributions...

**Comment by HoussameH** [comment]
Which paragraph are you referring to? Should I remove the ## What is geoclustering? paragraph ?

**Comment by kais-siala** [comment]
Yes, that one

**Comment by kais-siala** [comment]
@all-contributors please add @HoussameH for code, doc
@all-contributors please add @waleedskhan for code

**Comment by kais-siala** [comment]
@all-contributors please add @HoussameH for code, doc

**Comment by kais-siala** [comment]
@all-contributors please add @waleedskhan for code
